### ISSUE TITLE
New Features and Fixes TODO

### ISSUE THREAD

**Issue by egebilecen** [egebilecen/PZServerDiscordBot#16]
- [x] (Added with #22) ~~Add bot intents configuration screenshot to `README.md`. (PSA: Enable all intents. Otherwise bot might not work properly.)~~ 
- [x] (Added with #38) ~~Fix restart announcer. It announces `1 min left` message two times as announcer's interval is 30 seconds.~~
- [x] (Added with #38) ~~Improve restart announcer logic. For example, it announces `15 min left` meanwhile 10 min left for the server restart. (This isn't issue with automated server restarts but when a mod update detected, bot owner might have set it to a value that isn't in announcement minute list which will cause the nearest minute in list to be announced. Just like the given example.)~~
- [x] (Added with #26) ~~Prevent being able to set command and log channel into same channel. With #14, bot no longer responds to channels that has no commands assigned into them which is the case for the log channel as well. `Note: You should still able to use !set_log_channel command in command channel without any issues.`~~
- [x]  (Added with #21) ~~People are able to change their server's main directory in `server.bat` file with `-Duser.home=<path>` parameter. Example: `-Duser.home=D:\Server1_Data`. Take this into considiration when parsing server `.ini` files.~~
- [x] (Added with #26) ~~Add a new command to see schedules' next execute time in minutes.~~
- [x] (Added with #26) ~~Update bot version checker to send messages to command channel, not log channel. (Check if last message sent to the command channel is new version available message. If not, send message)~~
- [x] (Added with #26) ~~Reduce message spam for workshop mod unlisted/private messages. (Perhaps make them being sent every day or when mod list updated)~~
- [x] (Added with #26) ~~Add `!bot_info` command to public channel. It will print out bot information and repo link.~~
- [x] (Added with #26) ~~Add semantic version class for performing efficient version checks.~~
- [ ] Add filewatcher class. Will be used later for parsing log files.
- [ ] Add in-game chat mirroring feature. (As a toggleable feature)
- [ ] Add in-game notification mirroring feature. (As a toggleable feature. Such as logins, disconnects, deaths and perk changes)
- [ ] Add feature to adding rotating auto announcement messages. (Messages will be announced in game.)
- [ ] Add new command to update the bot to new version when server is not running.
- [x] (Added with #38) ~~Update logging function to print out formatted string with date. This removes the need of getting and formatting date manually.~~
- [x] (Added with #38) ~~Add a separate notification for pre-release version of bot to version checker.~~
- [x] (Added with #43) ~~Add translation system. (And mention it in README)~~

**Comment by egebilecen** [comment]
I am no longer planning to add new features to this bot as I am quite busy in real life and have no incentive to work on this bot anymore, unlike in the past. So I am closing this issue for now.
